[OPS-5793] This dir successfullu bakes solr 7 and solr 8 images. Howe…
UN-OCHA/docker-images pull request #209
Opened 2019-07-12 05:19 UTC by cafuego

…ver, it should get a new image image.

2019-07-12 19:25 UTC, teodorescuserban commented
Ignoring the PR at @cafuego request. Please ping when review is needed.

2019-07-16 06:04 UTC, cafuego commented
Pingelingeling!  Built on all-new Alpine 3.10.1 / Java 11 base images.

2019-07-16 08:03 UTC, teodorescuserban requested changes
other than those two minor changes it looks great!

2019-07-16 08:03 UTC, teodorescuserban commented on alpine-solr/7/Dockerfile.tmpl
> +MAINTAINER Serban Teodorescu <teodorescu.serban@gmail.com>
maintainer keyword is being deprecated. and i am not the only maintainer. :)

2019-07-16 08:05 UTC, teodorescuserban requested changes
hm thats the second change.

2019-07-16 08:05 UTC, teodorescuserban commented on alpine-base-jdk/openjdk/Dockerfile.tmpl
> +      openjdk${VERSION}-jre && \
ugh, use headless jre.

2019-07-17 05:38 UTC, cafuego commented on alpine-base-jdk/openjdk/Dockerfile.tmpl
> +      openjdk${VERSION}-jre && \
Yeah, that's what it installs.

2019-07-26 00:22 UTC, merged