[OPS-8056] xz sure why not
UN-OCHA/docker-images pull request #292
Opened 2022-01-28 03:12 UTC by cafuego

2022-01-28 03:34 UTC, orakili approved these changes, later dismissed
Looks good to me.

2022-01-28 05:39 UTC, orakili requested changes
Looks like they separated the content into at least 2 mandatory packages: https://github.com/just-containers/s6-overlay#quickstart:

- `s6-overlay-noarch-$VERSION-tar.xz`
- `s6-overlay-$ARCH-$VERSION-tar.xz`

2022-01-28 05:39 UTC, orakili commented on alpine-base-s6/Dockerfile.tmpl
> +    curl -o /tmp/s6-overlay.tar.xz -jkSL https://github.com/just-containers/s6-overlay/releases/download/v${S6VERSION}/s6-overlay-${S6ARCH}-${S6VERSION}.tar.xz && \
```suggestion
    curl -o /tmp/s6-overlay-noarch.tar.xz -jkSL https://github.com/just-containers/s6-overlay/releases/download/v${S6VERSION}/s6-overlay-noarch-${S6VERSION}.tar.xz && \
    tar xJf /tmp/s6-overlay-noarch.tar.xz -C / && \
    curl -o /tmp/s6-overlay.tar.xz -jkSL https://github.com/just-containers/s6-overlay/releases/download/v${S6VERSION}/s6-overlay-${S6ARCH}-${S6VERSION}.tar.xz && \
```

2022-01-28 07:00 UTC, cafuego commented
Welp, poopie. Thanks for the fix :-)

2022-01-28 07:30 UTC, orakili approved these changes, later dismissed
That seems ok now but it would be good to have someone else test as well to confirm.

2022-01-28 08:21 UTC, orakili commented
Sorry, dismissing my review again. While the images based on this `alpine-base-s6` now start with the added `noarch`, images starting `nginx` like the `php-k8s` images seems to not work. For example `netstat -tulpn` inside a container running such image doesn't show `nginx` listening on port 80 for example.


That may not be an issue withe s6-overlay but I need to investigate more...

2022-01-28 08:58 UTC, teodorescuserban commented
> Sorry, dismissing my review again. While the images based on this `alpine-base-s6` now start with the added `noarch`, images starting `nginx` like the `php-k8s` images seem to not work. For example `netstat -tulpn` inside a container running such image doesn't show `nginx` listening on port 80 for example and curl for example fails with a `Connection refused`.
> 
> That may not be an issue withe s6-overlay but I need to investigate more...
> 
> Advice: read the https://github.com/just-containers/s6-overlay README.md because they changed a lot of things in 3.0.0.0 and it looks like all the `run_xxx` scripts that we used to put in /etc/services.d need to be modified: https://github.com/just-containers/s6-overlay#writing-a-service-script

It does say "We encourage you to switch to the new format, but if you don't need its benefits, you can stick with regular service directories in /etc/services.d, it will work just as well." so nothing breaking there, right?

2022-01-28 09:02 UTC, orakili commented
That's what they say but in practice, even with the "compatibility" assets mentioned in the installation section: https://github.com/just-containers/s6-overlay#installation, I could not get any images with nginx to listen the ports.

But maybe I broke something else.

2022-01-30 23:01 UTC, cafuego commented
I did a build and I think I see the problem, the run scripts aren't executable. Fixing and re-testing.

2022-01-30 23:05 UTC, cafuego commented
And all the helper scripts are now in /package/admin/s6/* and symlinked from /command. So the run scripts will indeed all need updating. Sigh.

2022-01-31 01:18 UTC, cafuego commented
And annoyingly v3 overwites any PATH value to try to pass via an env var. That breaks all our stacks (they need /srv/www/vendor/bin) and I don't want to dump that in the new global config file either, so I've included a hacked up `/init` that doesn't reset PATH and ignore what we want.  Also added a whiny comment to the s6-overlay repo and hopefully my fix will get in to the next version.

In the mean time, the current HEAD of this branch should be able to build you a working Raspberry Pi image.

2022-01-31 08:55 UTC, teodorescuserban commented
For NodeJS, I just grabbed the v2.2.0.3 os s6-overlay and thats that. I don't think it's worth the time to rewrite all the stratup scripts and locations just for the sake of running s6-overlay v3.x.

2022-01-31 08:57 UTC, teodorescuserban commented
> I did a build and I think I see the problem, the run scripts aren't executable. Fixing and re-testing.

That's going to create issues as well if the scripts are mapped from the docker compose stack. Probably a better approach to add a pre-init script to make those `run` scripts executable.

2022-02-01 01:38 UTC, orakili commented
Note, they are probably going to change the URLs again and remove the version from the filenames: https://github.com/just-containers/s6-overlay/issues/386#issuecomment-1026245231.

2022-02-01 07:43 UTC, teodorescuserban approved these changes, later dismissed

2022-02-28 16:46 UTC, teodorescuserban approved these changes

2025-12-25 21:02 UTC, closed without merging