Cleanup - alpine-base-postgis
UN-OCHA/docker-images pull request #61
Opened 2016-09-27 05:32 UTC by orakili

- Change apk package testing download link to use CDN.
- Use "virtual" package to regroup build dependencies to ease removal.

2016-10-22 13:49 UTC, teodorescuserban requested changes
apparently you are not cleaning up a bunch of packages:
geos-dev libxml2-dev gdal-dev proj4-dev gcc make libgcc g++

2016-10-24 01:12 UTC, orakili commented
@teodorescuserban Thanks and sorry about that. It's fixed in https://github.com/UN-OCHA/docker-images/pull/61/commits/5eda998c05f9fcd7c04c4f440012ffc74297e5e1.

2016-11-30 09:18 UTC, emmajane commented
@orakili can you review if this pull request is still needed?

2016-12-16 09:33 UTC, orakili commented
@emmajane Sorry for the late reply. This PR still brings a bit of consistency in the package management but it doesn't reduce the number of layers so it could be skipped.

2016-12-16 11:57 UTC, emmajane commented
Per @orakili's comment, closing the PR.

2016-12-16 11:57 UTC, closed without merging